[build]
builder = "dockerfile"

[deploy]
startCommand = "java -jar target/issue-tracker-1.0.0.jar"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
SPRING_PROFILES_ACTIVE = "production"
PORT = "8080"