[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "java -jar target/issue-tracker-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
SPRING_PROFILES_ACTIVE = "production"
