services:
  - type: web
    name: issue-tracker
    env: java
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/issue-tracker-1.0.0.jar
    healthCheckPath: /health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
      - key: JAVA_VERSION
        value: 17
      - key: MAVEN_OPTS
        value: "-Xmx1024m"